#!/usr/bin/env bash

set -eEu -o pipefail

status() {
    echo "### $1"
}

runTerser() {
    terser --mangle-props regex=/^_/ --ecma 6 --compress --mangle --module ${@+"$@"}
}

status "Clean"
rm -rf dist/

status "Compile"
tsc

status "Build module"
rollup dist/inject-hooks.js --file dist/inject-hooks.mjs --format esm
runTerser --module -o dist/inject-hooks.min.mjs dist/inject-hooks.mjs

status "Build UMD"
rollup dist/inject-hooks.js --file dist/inject-hooks.umd.js --format umd --name InjectHooks
runTerser -o dist/inject-hooks.umd.min.js dist/inject-hooks.umd.js
